language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t francocarini/docker-frontend-test -f Dockerfile.dev .
script:
  - docker run -e CI=true francocarini/docker-frontend-test npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-frontend-test"
  env: "DockerFrontendTest-env"
  bucket_name: "elasticbeanstalk-us-east-2-347261847824"
  bucket_path: "docker-frontend-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
